### ISSUE TITLE
integrar funciones para leer/escribir en server con `{arrow}`

### ISSUE THREAD

**Issue by pablotis** [dnme-minturdep/herramientas#16]

**Comment by TuQmano** [comment]
Esto ya está resuelto acá, no  @eliansoutu ? https://github.com/dnme-minturdep/herramientas/commit/5c7cae657df9f73651e11c6fabcbf9f276b26c41

**Comment by eliansoutu** [comment]
Sí para leer/escribir archivos `.parquet` (no datasets enteros)

**Comment by TuQmano** [comment]
Cerramos esto @pablotis ? Si es que se quiere trabajar con [datasets](https://arrow.apache.org/docs/r/articles/dataset.html) abrimos nuevo _issue_ y referenciamos este?

**Comment by pablotis** [comment]
Dale, cerramos hasta que surja nueva necesidad
